Documentation update: add readthedocs with sphinx
rctn/sparsecoding pull request #84
Opened 2024-11-28 16:15 UTC by belsten

I've added sphinx support with autodoc and autosummary with utilizes inline code blocks to generate documentation. In addition to this, I've added three additional pages with provide background info:

* `docs/install.rst`: goes though installation procedure 
* `docs/quickstart.rst`: provides high-level info regarding repo structure, and pointer to notebooks
* `docs/contributing.rst`: info regarding how to contribute (largely from `docs/contributing.md` - which is now deleted - and includes some updates)

Updated the readme to provide pointers to these new resources and added some additional information about the repo. 

I also updated the `__init__.py` such that they import library functionalities, such that tab autocomplete works in IPython.

2025-02-01 21:44 UTC, 9q9q requested changes
Thanks so much Alex, this is awesome!! Just some minor comments, mostly just to make sure all the documentation is up to date with the recent restructuring PRs and slight changes to installation setup etc.

I think we can continue to edit the wording in the documentation as we go but no need for any major changes in this PR.

2025-02-01 21:44 UTC, 9q9q commented on docs/index.rst
> +We believe that sharing code within the scientific community is an important
delete?

2025-02-01 21:44 UTC, 9q9q commented on docs/install.rst
> +Installation
same as readme, update with https://github.com/rctn/sparsecoding/pull/91

2025-02-01 21:44 UTC, 9q9q commented on sparsecoding/inference/iht.py
> +    sparsity : scalar (1,)
is there a reason to show the size for scalar and string (line 20)? if so, should do consistently across docstrings. if not, can remove (can do this in a separate pr if it's too much for this one)

2025-02-01 21:44 UTC, 9q9q commented on sparsecoding/inference/iht.py
> +        returns all coefficients during inference procedure if True
i can see this being slightly confusing (which dimension does "all" refer to), maybe change wording to something like "returns coefficients for all inference steps"
and also do for all methods with this arg

btw there are some inconsistencies with this arg across inference methods so i opened another issue i can fix separately https://github.com/rctn/sparsecoding/issues/93

2025-02-03 21:08 UTC, belsten commented on docs/contributing.rst
> +#. Clone the ``main`` branch.
This is up to date with the changes of #89.

2025-02-03 21:09 UTC, belsten commented on docs/index.rst
> +We believe that sharing code within the scientific community is an important
Deleted.

2025-02-03 21:13 UTC, belsten commented on sparsecoding/inference/iht.py
> +    sparsity : scalar (1,)
Fixed.

2025-02-03 21:14 UTC, belsten commented on sparsecoding/inference/iht.py
> +        returns all coefficients during inference procedure if True
Thanks for making this issue. I think it's beyond the scope of this PR. Moreover, `return_all_coefficients` for IHT doesn't work as of right now.

2025-02-07 22:14 UTC, ivanov approved these changes

2025-02-07 23:37 UTC, merged